### ISSUE TITLE
ReadMe English Translation

### ISSUE THREAD

**Issue by TPS** [Akamaru/Pi-Hole-Lists#12]
@Akamaru IfF interested, I embedded an English translation of [the ReadMe](https://github.com/Akamaru/Pi-Hole-Lists/blob/master/README.md) @ https://github.com/AdguardTeam/FiltersRegistry/issues/266#issue-531622212.

**Comment by Akamaru** [comment]
Hi, I don't think an English translation is necessary. Adding lists to pi-hole is not that difficult.
