### ISSUE TITLE
welt-im-wandel.tv

### ISSUE THREAD

**Issue by stonecrusher** [Akamaru/Pi-Hole-Lists#14]
Gehört das auch zu fakenewsde?
`welt-im-wandel.tv`
Bald 50 Mio views auf youtube und da werden hahnebüchene Thesen verbreitet. Die ganze Esoterik-Palette und natürlich üble Impfgegner.

Wäre bequem für mich, wenn's drin wäre, denn dann muss ich nicht bei allen PCs und Bekannten wieder was reinfummeln.

**Comment by Akamaru** [comment]
Habs mal hinzugefügt
